# Generated by Django 6.0.3 on 2026-03-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_status', models.CharField(choices=[('GEN', 'Generating'), ('FIN', 'Finished'), ('FAI', 'Failed')], default='GEN', max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('occasion', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('singer_voice_type', models.CharField(max_length=255)),
                ('mood', models.CharField(max_length=255)),
                ('track_length', models.PositiveIntegerField(default=0)),
                ('share_link', models.CharField(default='', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
