# Generated by Django 6.0.3 on 2026-04-25 14:33

import cithara.apps.song.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', validators=[cithara.apps.song.models.limit_total_songs, cithara.apps.song.models.limit_generating_song]),
        ),
        migrations.AlterField(
            model_name='song',
            name='share_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
